### ISSUE TITLE
Key assignments hardcoded to Retropad

### ISSUE THREAD

**Issue by zach-morris** [libretro/mame2016-libretro#10]
It looks like there are 4 retropad buttons hard coded to keyboard inputs in MAME2016 (and MAME2014):
RETROPAD_L2: TAB
RETROPAD_R2: F11
RETROPAD_L3: F2
RETROPAD_R3: F3

There's no way I could find to change this mapping either in retroarch or in a MAME.cfg.  This is a problem when mapping buttons for more than one controller / multiplayer games because the same action occurs for both players when any one of these buttons is pressed.

Is there a way around this?  Or is there an option that can be added in Retroarch to change the mapping to a JOYPAD input?

**Comment by markwkidd** [comment]
Related? https://github.com/libretro/mame2014-libretro/issues/37

**Comment by r-type** [comment]
I bet we can only do this for player 1 
and for the other players
 bind RETROPAD_L2/R2/L3/R3 to ITEM_ID_BUTTON9 /10/11/12
