### ISSUE TITLE
[build] version `GLIBC_2.29' not found (required by 3rdparty/genie/bin/linux/genie)

### ISSUE THREAD

**Issue by 5schatten** [libretro/mame2016-libretro#23]
After I've bumped my glibc version to the recent v2.29 lr-mame2016 fails to build for me. Looks like genie fails to locate the correct libm.so.6 or gets a wrong version? My package is based on lakkas and so I guess they'll run into the same problem once they rebase lakka 3.0 to LE9.x also libretro-mame fails to build too.

Package:
https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr/packages/5schatten/emulation-lr-cores/lr-mame2016/package.mk

Buildlog:
https://pastebin.com/hVjEJcvu

**Comment by MilhouseVH** [comment]
I've also created an issue upstream with `genie`: https://github.com/bkaradzic/GENie/issues/409

**Comment by 5schatten** [comment]
Fixed by https://github.com/LibreELEC/LibreELEC.tv/pull/3286/commits/29d3fa383035aa273b4d96abc386b0081607d99e
