### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by goyometeojorito** [libretro/mame2016-libretro#5]
Core do not support save states? but mame2003 yes, why mame2016 don't support save state?

**Comment by r-type** [comment]
2003  is an heavily upgraded core of an old mame version.
2016 core is an 0.174 version of mame with minimal change to run with libretro.
to be short , in 2016 savestates are done with mame internals features ,
and there is no plan to do this with RA features.
So shift + F7 to save , F7 to load.
